export enum InbuiltMessageCodes {
	WARNING_INPUT_FILE_NOT_FOUND = "FLS_W0001",
	INFO_INPUT_FILES_FOUND = "FLS_I0002",
	INFO_PREPARING_TO_INTREPET_FILES = "FLS_I0003",
	ERROR_FUNCTION_KEYWORD_MISSING = "FLS_E0004",
	ERROR_FUNCTION_NAME_MISSING = "FLS_E0005",
}